### ISSUE TITLE
code copied from LevelSelectionButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/making-tens#225] opened 2016-06-06 15:54 UTC
Noted while working on https://github.com/phetsims/vegas/issues/49...

MakingTensUtils, line 23:

```js
    /**
     * Code is copied over from LevelSelectionButton
     * Create a node that is scaled and padded out to meet the size specification.
     * @param {Image} icon
     * @param {Dimension2} size
     * @returns {*}
     */
    createSizedImageNode: function( icon, size ) {
```

We should not be copying code from common UI components. If there's something that needs to be publicly available, then create an issue (in this case, in vegas) and request that the functionality be made public.

**Comment by jonathanolson** [comment] 2016-10-07 15:44
Duplicate of https://github.com/phetsims/making-tens/issues/225

**Closed by jonathanolson** 2016-10-07 15:44 UTC
