### ISSUE TITLE
copy of vegas.LevelSelectionButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/making-tens#226] opened 2016-06-06 15:57 UTC
making-tens.LevelSelectionButton, line 6:

```js
 * The Vegas LevelSelectionButton is copied over to MakingTens, because of the need to display
 * the score in "Text", next  to the star symbol.
```

Do not copy common-code components. Open an issue to add functionality needed to those components.

**Comment by jonathanolson** [comment] 2016-10-07 15:44
Duplicate of https://github.com/phetsims/making-tens/issues/81

**Closed by jonathanolson** 2016-10-07 15:44 UTC
